"""Property-based test for "slugs are unique within a market" (Property 5).

The production :class:`app.models.company.Company` declares ``market`` as a
*native* Postgres enum and surrounds it with ``JSONB`` / ``PGUUID`` columns that
cannot be materialised on SQLite. So -- mirroring the convention used by
``test_external_refs_roundtrip_properties.py`` and
``test_verification_unverified_default_properties.py`` -- this test defines a
SQLite-friendly stand-in model that carries the *identical*
``UniqueConstraint("market", "slug")`` and the ``name`` / ``slug`` / ``market``
columns that :func:`app.services.companies.generate_unique_slug` reads. The
service's ``Company`` reference is monkeypatched to the stand-in, so the real
slug-generation and collision-suffixing logic runs against an in-memory
database.

The property (R1.3): for any set of company names created within a single
market -- including colliding, accented, and non-ASCII names -- the generated
slugs are pairwise distinct. A complementary test confirms uniqueness is *scoped
to the market*: the same names in two different markets may legitimately produce
identical slugs.

The stand-in's ``UniqueConstraint("market", "slug")`` is an independent backstop:
if ``generate_unique_slug`` ever returned a slug already present in the market,
the flush would raise ``IntegrityError`` and fail the test before the
pairwise-distinct assertion ran.

Validates: Requirements 1.3
"""

from __future__ import annotations

import pytest
import sqlalchemy as sa
from hypothesis import given, settings
from hypothesis import strategies as st
from sqlalchemy import create_engine
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column, sessionmaker
from sqlalchemy.pool import StaticPool

from app.models.enums import MarketKey
from app.services import companies


class _Base(DeclarativeBase):
    pass


class _CompanyStandIn(_Base):
    """SQLite-friendly stand-in for :class:`app.models.company.Company`.

    Carries only the columns the slug service touches -- ``name``, ``slug``,
    ``market`` -- plus the production ``UniqueConstraint("market", "slug")`` so
    the market-scoped uniqueness guarantee is enforced by the database exactly as
    it is in Postgres. ``market`` is a plain string here (the native enum is not
    needed: the service compares values for equality, not enum identity).
    """

    __tablename__ = "companies"
    __table_args__ = (sa.UniqueConstraint("market", "slug", name="uq_companies_market_slug"),)

    id: Mapped[int] = mapped_column(sa.Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(sa.String(256), nullable=False)
    slug: Mapped[str] = mapped_column(sa.String(256), nullable=False)
    market: Mapped[str] = mapped_column(sa.String(8), nullable=False)


def _build_session() -> tuple[Session, sa.Engine]:
    engine = create_engine(
        "sqlite+pysqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
        future=True,
    )
    _Base.metadata.create_all(engine)
    session_factory = sessionmaker(bind=engine, autoflush=False, expire_on_commit=False, future=True)
    return session_factory(), engine


def _create_company(db: Session, name: str, market: str) -> str:
    """Generate a market-unique slug for *name* and persist a stand-in row.

    Returns the assigned slug. The slug is generated by the production service
    (reading already-persisted rows to detect collisions) and the insert is
    flushed immediately so the next call sees it; the unique constraint would
    reject any duplicate the service failed to suffix.
    """

    slug = companies.generate_unique_slug(db, name, market)
    db.add(_CompanyStandIn(name=name, slug=slug, market=market))
    db.flush()
    return slug


# Names deliberately span the cases named by Property 5: direct collisions and
# case/punctuation/whitespace variants that slugify to the same stem; accented
# Latin text whose accents fold; and non-Latin scripts that transliterate or fall
# back to the shared empty-slug stem. Free-form printable ASCII fills in the rest
# of the input space.
_colliding = st.sampled_from(["Acme", "acme", "ACME", "  Acme  ", "Acme!!!", "a.c.m.e", "Acme Inc", "acme-inc"])
_accented = st.sampled_from(["Café Société", "Niño Über", "Łódź Group", "Señor Çaña", "naïve café", "Zürich AG"])
_non_ascii = st.sampled_from(["日本株式会社", "Москва ООО", "北京公司", "한국 회사", "شركة الأمل", "Ελλάδα ΑΕ"])
_freeform = st.text(alphabet=st.characters(min_codepoint=32, max_codepoint=126), min_size=1, max_size=40)

_name = st.one_of(_colliding, _accented, _non_ascii, _freeform)
# A set of company names created together; collisions are likely by construction.
_names = st.lists(_name, min_size=1, max_size=30)

_MZ = MarketKey.mz.value
_MX = MarketKey.mx.value


# Feature: multi-tenant-hiring-platform, Property 5: Slugs are unique within a market
@settings(max_examples=100, deadline=None)
@given(names=_names)
def test_slugs_are_unique_within_a_market(names: list[str]) -> None:
    """For any set of company names created within a single market -- including
    colliding, accented, and non-ASCII names -- the generated slugs are pairwise
    distinct.

    Validates: Requirements 1.3
    """

    db, engine = _build_session()
    original = companies.Company
    companies.Company = _CompanyStandIn
    try:
        slugs = [_create_company(db, name, _MZ) for name in names]

        # Pairwise distinctness: no two companies in the market share a slug.
        assert len(slugs) == len(set(slugs)), f"duplicate slug generated within market: {slugs}"

        # The database agrees: one row per generated slug, all within the market.
        rows = db.execute(sa.select(_CompanyStandIn.slug).where(_CompanyStandIn.market == _MZ)).scalars().all()
        assert sorted(rows) == sorted(slugs)
        assert len(set(rows)) == len(rows)
    finally:
        companies.Company = original
        db.close()
        engine.dispose()


# Feature: multi-tenant-hiring-platform, Property 5: Slugs are unique within a market
@settings(max_examples=100, deadline=None)
@given(names=_names)
def test_slug_uniqueness_is_scoped_to_the_market(names: list[str]) -> None:
    """Uniqueness is scoped *per market*: creating the same ordered names in two
    different markets yields identical slug sequences -- a collision across
    markets is allowed -- while each market's slugs remain pairwise distinct.

    Validates: Requirements 1.3
    """

    db, engine = _build_session()
    original = companies.Company
    companies.Company = _CompanyStandIn
    try:
        mz_slugs = [_create_company(db, name, _MZ) for name in names]
        mx_slugs = [_create_company(db, name, _MX) for name in names]

        # Within each market, slugs are unique.
        assert len(mz_slugs) == len(set(mz_slugs))
        assert len(mx_slugs) == len(set(mx_slugs))

        # Scoped uniqueness: the two markets resolve the identical name sequence
        # independently, so they produce the identical slug sequence -- proving a
        # slug used in one market may freely recur in another.
        assert mz_slugs == mx_slugs
    finally:
        companies.Company = original
        db.close()
        engine.dispose()


if __name__ == "__main__":  # pragma: no cover - convenience for ad-hoc runs
    pytest.main([__file__, "-v"])
